### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by guyanooph** [gyoerkaa/mdltools#1]
I want to import a mdl file of dota2 into blender,  but dont work.

It show me this message:

---

UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 9: illegal multibyte sequence
location: <unknown location>:-1

---

What can i do for this?
Thank you!

**Comment by gyoerkaa** [comment]
Ugh sorry, this was made for Aurora Engine mdl files. It will not work for Half Life or Dota2 mdl files. Unfortunately they are completely different. 

Up until now I wasn't aware that Dota2 also had mdl file extensions. I will update the project description.
